server:
  port: ${SERVER_PORT:9088}
  servlet:
    context-path: /authentication
spring:
  application:
    name: ${APPLICATION_NAME:Auth-Service-App}
  datasource:
#    url: ${DATABASE_HOST:jdbc:mysql://localhost:3306/:}${DATABASE_NAME:authServiceApp_DB}
#    username: ${USERNAME:root}
#    password: ${PASSWORD:****}
#    driver-class-name: ${DATABASE_DRIVER:com.mysql.jdbc.Driver}
     url: jdbc:mysql://localhost:3306/authServiceApp_DB
     username: root
     password: #####
     driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  sql:
    init:
      mode: always
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
#  instance:
#    hostname: ${EUREKA_HOST:localhost}
#    prefer-ip-address: true

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}

app:
  token:
    jwt:
      expires: ${TOKEN_EXPIRES:95000}
      private-key: |
        -----BEGIN PRIVATE KEY-----
        -----END PRIVATE KEY-----
      public-key: |
        -----BEGIN PUBLIC KEY-----
        -----END PUBLIC KEY-----